CrudSemBD/Models/PessoaModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CrudSemBD.Models
{
    public class PessoaModel
    {
        [Key]
        public int idPessoa { get; set; }

        [ForeignKey("Sexo")]
        public int idSexo { get; set; }
        public string nmPessoa { get; set; }
        public DateTime dtNascimento { get; set; }
        public string pessoaCPF { get; set; }
        public virtual SexoModel Sexo { get; set; }
    }
}

CrudSemBD/Models/SexoModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudSemBD.Models
{
    public class SexoModel
    {
        [Key]
        public int idSexo { get; set; }
        public string descricaoSexo { get; set; }

        public virtual ICollection<PessoaModel> Pessoas { get; set; }

        public SexoModel()
        {
            Pessoas = new HashSet<PessoaModel>();
        }
    }
}

CrudSemBD/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CrudSemBD.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CrudSemBD/Controllers/PessoaController.cs
using CrudSemBD.Context;
using CrudSemBD.Models;
using CrudSemBD.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CrudSemBD.Controllers
{
    public class PessoaController : Controller
    {
        // GET: Pessoa
        public ActionResult Index()
        {
            using (var contexto = new DBCrud())
            {
                var buscaPessoas = contexto.Pessoas.AsNoTracking().ToList();
                var pessoaViewModel = new List<PessoaViewModel>();

                if (buscaPessoas != null)
                {
                    foreach (var item in buscaPessoas)
                    {
                        pessoaViewModel.Add(new PessoaViewModel
                        {
                            idPessoa = item.idPessoa,
                            idSexo = item.idSexo,
                            dtNascimento = item.dtNascimento.ToString("dd/MM/yyy"),
                            nmPessoa = item.nmPessoa,
                            pessoaCPF = item.pessoaCPF,
                            descricaoSexo = item.Sexo.descricaoSexo
                        });
                    }
                }

                return View(pessoaViewModel);
            }
        }

        // GET: Pessoa/Details/5
        public ActionResult Details(int id)
        {
            var buscaPessoa = BuscaPessoaById(id);
            var pessoaViewModel = new PessoaViewModel();

            if(buscaPessoa == null)
            {
                return View();
            }

            pessoaViewModel.idPessoa = buscaPessoa.idPessoa;
            pessoaViewModel.nmPessoa = buscaPessoa.nmPessoa;
            pessoaViewModel.idSexo = buscaPessoa.idSexo;
            pessoaViewModel.dtNascimento = buscaPessoa.dtNascimento.ToString("dd/MM/yyyy");
            pessoaViewModel.pessoaCPF = buscaPessoa.pessoaCPF;
            pessoaViewModel.descricaoSexo = buscaPessoa.Sexo.descricaoSexo;

            return View(pessoaViewModel);
        }

        // GET: Pessoa/Create
        public ActionResult Create()
        {
            PreencherViewBag();

            return View();
        }

        // POST: Pessoa/Create
        [HttpPost]
        public ActionResult Create(PessoaViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using(var context = new DBCrud())
                    {
                        context.Pessoas.Add(new PessoaModel
                        {
                            nmPessoa = model.nmPessoa,
                            dtNascimento = Convert.ToDateTime(model.dtNascimento),
                            idPessoa = model.idPessoa,
                            idSexo = model.idSexo,
                            pessoaCPF = model.pessoaCPF
                        });

                        context.SaveChanges();
                    }
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Pessoa/Edit/5
        public ActionResult Edit(int id)
        {
            var buscaPessoa = BuscaPessoaById(id);
            var pessoaViewModel = new PessoaViewModel();

            if(buscaPessoa == null)
            {
                return View();
            }

            pessoaViewModel.idPessoa = buscaPessoa.idPessoa;
            pessoaViewModel.idSexo = buscaPessoa.idSexo;
            pessoaViewModel.dtNascimento = buscaPessoa.dtNascimento.ToString("dd/MM/yyyy");
            pessoaViewModel.pessoaCPF = buscaPessoa.pessoaCPF;
            pessoaViewModel.nmPessoa = buscaPessoa.nmPessoa;

            PreencherViewBag();

            return View(pessoaViewModel);

        }

        // POST: Pessoa/Edit/5
        [HttpPost]
        public ActionResult Edit(PessoaViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using(var context = new DBCrud())
                    {
                        var buscaPessoa = context.Pessoas.Find(model.idPessoa);

                        if(buscaPessoa != null)
                        {
                            buscaPessoa.idSexo = model.idSexo;
                            buscaPessoa.nmPessoa = model.nmPessoa;
                            buscaPessoa.pessoaCPF = model.pessoaCPF;
                            buscaPessoa.dtNascimento = Convert.ToDateTime(model.dtNascimento);

                            context.SaveChanges();
                        }
                    }
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Pessoa/Delete/5
        public ActionResult Delete(int id)
        {
            var buscaPessoa = BuscaPessoaById(id);
            var pessoaViewModel = new PessoaViewModel();
            
            if(buscaPessoa != null)
            {
                pessoaViewModel.idPessoa = buscaPessoa.idPessoa;
                pessoaViewModel.idSexo = buscaPessoa.idSexo;
                pessoaViewModel.dtNascimento = buscaPessoa.dtNascimento.ToString("dd/MM/yyy");
                pessoaViewModel.pessoaCPF = buscaPessoa.pessoaCPF;
                pessoaViewModel.nmPessoa = buscaPessoa.nmPessoa;
                pessoaViewModel.descricaoSexo = buscaPessoa.Sexo.descricaoSexo;
            }
          
            return View(pessoaViewModel);
        }

        // POST: Pessoa/Delete/5
        [HttpPost]
        public ActionResult Delete(PessoaViewModel model)
        {
            try
            {
                using(var context = new DBCrud())
                {
                    var buscaPessoa = context.Pessoas.Find(model.idPessoa);

                    if(buscaPessoa != null)
                    {
                        context.Pessoas.Remove(buscaPessoa);
                        context.SaveChanges();
                    }
                }

                return RedirectToAction("Index");
            }
            catch
            {                
                return View(model);
            }
        }

        public PessoaModel BuscaPessoaById(int id)
        {
            using (var contexto = new DBCrud())
            {
                var buscaPessoa = contexto.Pessoas.Include("Sexo").AsNoTracking().FirstOrDefault(x => x.idPessoa == id);

                if (buscaPessoa != null)
                {
                    return buscaPessoa;
                }

                return null;
            }
        }
        public void PreencherViewBag()
        {
            using (var context = new DBCrud())
            {
                ViewBag.listaSexo = context.Sexos.AsNoTracking().ToList();
            }
        }
    }
}

CrudSemBD/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CrudSemBD/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CrudSemBD/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CrudSemBD/Views/Pessoa/Create.cshtml
@model CrudSemBD.ViewModel.PessoaViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cadastrar - Pessoa</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.nmPessoa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nmPessoa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nmPessoa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.idSexo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.idSexo, new SelectList(ViewBag.listaSexo, "idSexo", "descricaoSexo"), new { @class = "form-control"})
            @Html.ValidationMessageFor(model => model.idSexo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.dtNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.dtNascimento, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.dtNascimento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.pessoaCPF, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.pessoaCPF, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.pessoaCPF, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Cadastrar" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CrudSemBD/Views/Pessoa/Delete.cshtml
@model CrudSemBD.ViewModel.PessoaViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Você tem certeza que deseja deletar esta Pessoa?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nmPessoa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nmPessoa)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.descricaoSexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descricaoSexo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dtNascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dtNascimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pessoaCPF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pessoaCPF)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.HiddenFor(model => model.idPessoa)
            <input type="submit" value="Deletar" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

CrudSemBD/Views/Pessoa/Details.cshtml
@model CrudSemBD.ViewModel.PessoaViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Informações - Pessoa</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nmPessoa)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.nmPessoa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descricaoSexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descricaoSexo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dtNascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dtNascimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pessoaCPF)
        </dt> 

        <dd>
            @Html.DisplayFor(model => model.pessoaCPF)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.idPessoa }) |
    @Html.ActionLink("Voltar", "Index")
</p>

CrudSemBD/Views/Pessoa/Edit.cshtml
@model CrudSemBD.ViewModel.PessoaViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Atualizar Informações - Pessoa</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.idPessoa)
    <div class="form-group">
        @Html.LabelFor(model => model.nmPessoa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nmPessoa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nmPessoa, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.idSexo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.idSexo, new SelectList(ViewBag.listaSexo, "idSexo", "descricaoSexo"), new { @class = "form-control"})
            @Html.ValidationMessageFor(model => model.idSexo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.dtNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.dtNascimento, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.dtNascimento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.pessoaCPF, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.pessoaCPF, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.pessoaCPF, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvar" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CrudSemBD/Views/Pessoa/Index.cshtml
@model List<CrudSemBD.ViewModel.PessoaViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Pessoas</h2>

<p>
    @Html.ActionLink("Cadastrar", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Nome:
        </th>
        <th>
            Sexo:
        </th>
        <th>
            Data nascimento:
        </th>
        <th>
            CPF:
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nmPessoa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.descricaoSexo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dtNascimento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.pessoaCPF)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new {  id=item.idPessoa }) |
            @Html.ActionLink("Detalhar", "Details", new { id=item.idPessoa }) |
            @Html.ActionLink("Deletar", "Delete", new {  id=item.idPessoa })
        </td>
    </tr>
}

</table>

CrudSemBD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CRUD-SemBD", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Pessoas", "Index", "Pessoa")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>